오늘의 임시 담당자 설정 api 구현
TeamHous/Hous-Server pull request #103
Opened 2022-07-13 16:50 UTC by yjooooo

## ✒️ 관련 이슈번호
- Closes #100

## 🔑 Key Changes
1.  tmpRuleMembers: ObjecItd[]으로 변경하기
    - Rule, RuleInfo 수정
3. 오늘의 임시 담당자 설정 api 구현

## 📢 To Reviewers
- 시간이 저는 왜 00시로 저장이 될까여...

2022-07-13 19:00 UTC, orijoon98 requested changes

2022-07-13 19:00 UTC, orijoon98 commented on src/models/Rule.ts
> -        },
이 부분 type, required, ref는 유지해야할거같아용...

2022-07-13 19:09 UTC, yjooooo commented on src/models/Rule.ts
> -        },
죄송합니다,, 내일 수정하겠습니다!

2022-07-13 19:29 UTC, hyejungg approved these changes

2022-07-13 19:29 UTC, hyejungg commented on src/routes/RoomRouter.ts
> +  [body('tmpRuleMembers').not().isEmpty()],
임시담당자는 여러명 할 수 있지 않나요?! not().isEmpty().isArray() 이렇게 해줘야 하지 않을까요?
1개만 받아도 배열 안에 받는 거 아닌가요!?!

2022-07-14 07:12 UTC, hyejungg commented on src/routes/RoomRouter.ts
> +  [body('tmpRuleMembers').not().isEmpty()],
죄송합니다 언니가 맞습니다 ......

2022-07-14 07:17 UTC, yjooooo commented on src/routes/RoomRouter.ts
> +  [body('tmpRuleMembers').not().isEmpty()],
빈 배열이 들어와야해서 not().isEmpty()로 가는걸로!

2022-07-14 07:32 UTC, orijoon98 approved these changes

2022-07-14 07:40 UTC, merged