오늘의 임시 담당자 조회 시 호미들 리스트 조회 api 구현
TeamHous/Hous-Server pull request #104
Opened 2022-07-13 18:45 UTC by yjooooo

## ✒️ 관련 이슈번호
- Closes #101

## 🔑 Key Changes
1. 오늘의 임시 담당자 조회 시 호미들 리스트 조회 api 구현

## 📢 To Reviewers
- 호다닥 만들고 잡니당

2022-07-13 19:54 UTC, orijoon98 requested changes
연주야... 그 담당자 리스트 불러올때 고정담당자도 고려를 해야할것같아유..
담당자가 표시된 경우에도 수정이 가능하다고 해서,
아직 임시담당자가 세팅 안되고, 고정담당자만 설정된 경우도 프로필들이 전부 표시가 돼야합니당..

2022-07-13 19:54 UTC, orijoon98 commented on src/interfaces/rule/HomiesWithIsTmpMemberResponseDto.ts
> +  homies: HomiesWithIsTmpMember[];
여기 규칙이름이 왜들어가나용??!!

2022-07-13 19:54 UTC, orijoon98 commented on src/models/Rule.ts
> -    ],
여기도 전 pr에서 말한거!

2022-07-13 19:56 UTC, hyejungg requested changes
코드 보고 살짝 헷갈려서 기획에게 물어보니 임시 담당자 팝업에서 고정담당자가 기존에 설정되어 있는 경우, 고정 담당자에 대해서 기본적으로 체크가 되어 있어야 한다고합니다.

해당 코드는 임시담당자 설정 팝업에서는 기존의 고정 담당자를 변경될 수 있다는 부분이 고려가 안된 것 같아요!

2022-07-13 19:56 UTC, hyejungg commented on src/services/RuleService.ts
> +    if (dayjs().isSame(rule.tmpUpdatedDate, 'day')) {
dayjs()객체는 시분초까지 갖는 데이트 객체일 것 같은데 isSame의 두번째 인자를 day로 주면 년월일까지만 검사하나요?!

2022-07-13 19:56 UTC, hyejungg commented on src/services/RuleService.ts
> +            isTmpMember: rule.tmpRuleMembers.includes(homie._id),
여기를 이렇게 주면 배열에 없으면 알아서 else에 있는 것처럼 isTmpMemeber 가 false로 들어가는거 아닌가요 ?! else를 또 지정하는 이유가 궁금하군요 .. !

이 코드는 좋은데 제대로 살리려면 굳이 if-else를 안해줘도 될 것 같은 느낌인데...!

2022-07-13 21:47 UTC, yjooooo commented on src/interfaces/rule/HomiesWithIsTmpMemberResponseDto.ts
> +  homies: HomiesWithIsTmpMember[];
팝업창 상단에 규칙 이름을 띄워줘야해서요!

2022-07-13 21:48 UTC, yjooooo commented on src/models/Rule.ts
> -    ],
네!! 수정하겠습니다!

2022-07-13 21:48 UTC, yjooooo commented on src/services/RuleService.ts
> +    if (dayjs().isSame(rule.tmpUpdatedDate, 'day')) {
네네! 뒤에 year을 주면 연도까지만 검사하고 그렇습니다!

2022-07-13 21:55 UTC, yjooooo commented on src/services/RuleService.ts
> +            isTmpMember: rule.tmpRuleMembers.includes(homie._id),
아 처음에는 map안에서 if문(tmpRuleMembers에 있는지 비교하는 부분)을 넣으려고 생각했어서 tmpUpdatedDate가 오늘이 아니라면 map안에 if문을 빼주고 싶어서 if else로 나눴었습니다!
그러다가 includes를 써야겠다 생각이 바뀌었는데 if else문이 필요없어졌다는 것을 캐치하지 못했어요ㅠㅠ 좋은 지적 김사합니다!

2022-07-14 11:11 UTC, orijoon98 approved these changes
고생했네유~! 깔끔

2022-07-14 12:47 UTC, hyejungg approved these changes
최고최고 ! 고생했당 !

2022-07-14 12:56 UTC, merged