유저 탈퇴하기 api 구현 및 그 외 수정
TeamHous/Hous-Server pull request #144
Opened 2022-07-16 20:43 UTC by hyejungg

## ✒️ 관련 이슈번호
- Closes #132

## 🔑 Key Changes
1. 유저 탈퇴하기 api 구현
2. 디폴트 성향 조회 후 변경
3. userId가 null일수도 있는 경우를 고려해서 변경

## 📢 To Reviewers
- 코드 리뷰 꼼꼼히 ^^&

2022-07-16 21:20 UTC, orijoon98 requested changes

2022-07-16 21:20 UTC, orijoon98 commented on src/services/room/RoomRetrieveService.ts
이 부분은 클라가 보낸 roomId가 존재하는 방인지 확인하는 로직 아니었나용..?

2022-07-16 21:20 UTC, orijoon98 commented on src/services/room/RoomRetrieveService.ts
> +    }
이부분 혹시 checkForbiddenRoom으로 사용안한 이유가 있나용?

2022-07-16 21:20 UTC, orijoon98 commented on src/services/user/UserService.ts
> +      }
오홍.. 굳굳

2022-07-16 21:20 UTC, orijoon98 commented on src/services/user/UserService.ts
> +      // 유저 삭제
하잉 지워야해보림 ㅎㅎㅎ

2022-07-17 05:34 UTC, hyejungg commented on src/services/room/RoomRetrieveService.ts
맞습니다 테스트 해보면서 여기저기 수정한 것 같아요! 다시 돌려두겠습니다!

2022-07-17 05:48 UTC, hyejungg commented on src/services/room/RoomRetrieveService.ts
> +    }
곰곰히 생각해보았는데 다시 반영해두겠습니다!

2022-07-17 08:08 UTC, orijoon98 approved these changes
수고했어요 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ

2022-07-17 08:47 UTC, yjooooo requested changes
고생했습니당!!!

2022-07-17 08:47 UTC, yjooooo commented on src/controllers/UserController.ts
> +      .send(util.success(statusCode.OK, message.DELETE_USER, null));
DELETE_USER_SUCCESS 로?? ㅎㅎㅎㅎ

2022-07-17 08:47 UTC, yjooooo commented on src/modules/responseMessage.ts
> +  DELETE_USER: '사용자 탈퇴 성공입니다.',
요기!!

2022-07-17 08:47 UTC, yjooooo commented on src/services/user/UserService.ts
> +        }
배웠어영 구욷

2022-07-17 08:47 UTC, yjooooo commented on src/services/user/UserService.ts
> +
진짜 우리를 힘들게했던,, 결국 성공쓰

2022-07-17 08:58 UTC, yjooooo approved these changes

2022-07-17 09:08 UTC, merged