#13 [feat] 규칙 카테고리 추가 api 구현
TeamHous/Hous-Server pull request #23
Opened 2022-07-07 18:23 UTC by yjooooo

## ✒️ 관련 이슈번호
- Closes #16

## 🔑 Key Changes
1. 내용
   - 규칙 카테고리 추가 api 구현

## 📢 To Reviewers
- 드디어 첫 api 구현...!

2022-07-07 18:28 UTC, hyejungg approved these changes
고생했수당

2022-07-07 18:28 UTC, hyejungg commented on src/controllers/RuleController.ts
> +  const ruleCategoryCreateDto = req.body;
return type 명시해주면 좋겠다 ... !!

2022-07-07 18:28 UTC, hyejungg commented on src/services/RuleService.ts
> +    if (conflictCategory) {
👍

2022-07-07 18:28 UTC, hyejungg commented on src/interfaces/rule/RuleService.ts
> +import errorGenerator from '../errors/errorGenerator';
이 파일은 삭제 부탁드려요1

2022-07-07 18:33 UTC, orijoon98 requested changes

2022-07-07 18:33 UTC, orijoon98 commented on src/controllers/RuleController.ts
> + */
이 부분 access Private!
auth 인증 필요한게 Private이라고 정아님한테 들었어서..

2022-07-07 18:33 UTC, orijoon98 commented on src/services/RuleService.ts
> +    const room: RoomInfo | null = await Room.findById(roomId);
우리 도메인 관련 아이들은 타입 지정 안해주기로 하지 않았었나?!!

2022-07-07 18:33 UTC, orijoon98 commented on src/services/RuleService.ts
> +    }
나는 이렇게 에러 던지는 부분 if 중괄호 다 빼고 했었는데 어느 쪽으로든 통일하는게 좋을거같은데 어떠신지용

2022-07-07 18:33 UTC, orijoon98 commented on src/services/RuleService.ts
> +    const conflictCategory: RuleCategoryInfo | null =
여기도 타입!

2022-07-07 18:33 UTC, orijoon98 commented on src/services/RuleService.ts
> +    const data = {
response 이 형태로 할거면 이런 친구들은 response dto 따로 만들어서 타입 지정해주면 좋을거같아용~~

2022-07-07 18:35 UTC, yjooooo commented on src/controllers/RuleController.ts
> +  const ruleCategoryCreateDto = req.body;
넵!! 바로 반영!!

2022-07-07 18:36 UTC, yjooooo commented on src/interfaces/rule/RuleService.ts
> +import errorGenerator from '../errors/errorGenerator';
바로 삭제 하핳

2022-07-07 18:37 UTC, yjooooo commented on src/controllers/RuleController.ts
> + */
오호!! 맞네여!!!

2022-07-07 18:39 UTC, yjooooo commented on src/services/RuleService.ts
> +    const room: RoomInfo | null = await Room.findById(roomId);
넵!!!

2022-07-07 18:42 UTC, yjooooo commented on src/services/RuleService.ts
> +    }
넵!!! 좋습니다!

2022-07-07 18:43 UTC, yjooooo commented on src/services/RuleService.ts
> +    const conflictCategory: RuleCategoryInfo | null =
넵!!

2022-07-07 18:53 UTC, yjooooo commented on src/services/RuleService.ts
> +    const data = {
오호 좋은 것 같아요! 반영하겠습니다!

2022-07-07 18:57 UTC, hyejungg approved these changes
interace/rule/.DS_Store만 삭제해주시고 머지하시면 될 것 같습니다!

2022-07-07 19:03 UTC, hyejungg approved these changes

2022-07-08 03:57 UTC, orijoon98 requested changes

2022-07-08 03:57 UTC, orijoon98 commented on src/interfaces/rulecategory/RuleCategoryResponseDto.ts
> +}
response에는 _id도 포함해주는게 좋을거같은데 extend 사용해서 _id만 추가해줘도 좋을듯요~~

2022-07-08 03:57 UTC, orijoon98 commented on src/services/RuleService.ts
>      };
ruleCategoryId !!

2022-07-08 04:03 UTC, yjooooo commented on src/services/RuleService.ts
>      };
아 어제 혜정이랑 야밤 작업하더니 미쳤나봐 ㅋㅋㅋㅋㅋㅋㅋ

2022-07-08 04:03 UTC, yjooooo commented on src/interfaces/rulecategory/RuleCategoryResponseDto.ts
> +}
넵!!!!

2022-07-08 04:04 UTC, orijoon98 commented on src/services/RuleService.ts
>      };
눙물.....

2022-07-08 05:48 UTC, hyejungg approved these changes
우리 하우스 서버 짱야.

2022-07-08 05:48 UTC, hyejungg commented on src/modules/checkObjectIdValidation.ts
> +const ObjectId = mongoose.Types.ObjectId;
너 무 좋 아 요

2022-07-08 05:48 UTC, hyejungg commented on src/services/RuleService.ts
> +        statusCode: statusCode.BAD_REQUEST
굿!

2022-07-08 05:48 UTC, hyejungg commented on src/services/RuleService.ts
> +    const validRoomId = isValidObjectId(roomId);
boolean 같은 명확한 변수는 타입 지정 안하기로 했던가요.. ?! 그렇담 넘어가주시고 아니라면 25번 라인도 .. ?

2022-07-08 05:49 UTC, orijoon98 requested changes

2022-07-08 05:49 UTC, orijoon98 commented on src/modules/checkObjectIdValidation.ts
> +};
그 errorGenerator를 여기 return false 부분에 던지는게 서비스 로직에서 사용하기 좋을거같아서
return 타입을 void로 바꾸고 유효하지 않은 경우에 errorGenerator throw하는 식으로 변경하면 어떨까요

2022-07-08 05:49 UTC, orijoon98 commented on src/services/RuleService.ts
> +        statusCode: statusCode.BAD_REQUEST
위에 말한대로 수정하면 여기서 그냥 checkValidObjectId(roomId); 
이런식으로 쓰고 넘어가면 될거같아용

2022-07-08 05:50 UTC, yjooooo commented on src/modules/checkObjectIdValidation.ts
> +};
오키오키!

2022-07-08 05:50 UTC, yjooooo commented on src/services/RuleService.ts
> +        statusCode: statusCode.BAD_REQUEST
굳굳!!

2022-07-08 06:01 UTC, orijoon98 approved these changes
굳굳~~!!

2022-07-08 06:02 UTC, hyejungg approved these changes
❤️‍🔥

2022-07-08 06:03 UTC, merged